import {
  Category,
  Brand,
  ProductModel,
  AttributeGroup,
  AttributeValue,
  Product,
  ProductColor,
  PickupPoint,
  Promotion,
  Promocode,
  ShopSettings,
  AdminUser,
} from '../types';

export const INITIAL_SETTINGS: ShopSettings = {
  welcome_title: 'Добро пожаловать в Puff Paradise Shop',
  welcome_description:
    'У нас есть все что тебе нужно : жидкости, одноразки, POD и многое другое! Каталог по линейкам, быстрый заказ и доставка. Множество акций и промокодов. Удобные способы оплаты.',
  logo_url: '',
  delivery_price: 5.0,
  free_delivery_min_items: 4,
  manager_username: 'puff_mngr',
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 1, slug: 'liquid', name: 'Жидкости', icon: '🧪', sort_order: 1, is_active: true },
  { id: 2, slug: 'accessories', name: 'Комплектующие', icon: '🔧', sort_order: 2, is_active: true },
  { id: 3, slug: 'pod', name: 'Pod-системы', icon: '💨', sort_order: 3, is_active: true },
  { id: 4, slug: 'disposable', name: 'Одноразки', icon: '⚡', sort_order: 4, is_active: true },
  { id: 5, slug: 'snus', name: 'Снюс', icon: '🫧', sort_order: 5, is_active: true },
];

export const INITIAL_BRANDS: Brand[] = [
  // Жидкости
  { id: 1, slug: 'husky', name: 'Husky White / Mint', category_slug: 'liquid', sort_order: 1, is_active: true },
  { id: 2, slug: 'podonki', name: 'Подонки v2', category_slug: 'liquid', sort_order: 2, is_active: true },
  { id: 3, slug: 'maxwells', name: 'Maxwells', category_slug: 'liquid', sort_order: 3, is_active: true },
  { id: 4, slug: 'boshki', name: 'Бошки', category_slug: 'liquid', sort_order: 4, is_active: true },
  { id: 5, slug: 'glitch-sauce', name: 'Glitch Sauce', category_slug: 'liquid', sort_order: 5, is_active: true },
  { id: 6, slug: 'chappa', name: 'Chappa', category_slug: 'liquid', sort_order: 6, is_active: true },
  { id: 7, slug: 'hotspot', name: 'Hotspot Fuel', category_slug: 'liquid', sort_order: 7, is_active: true },

  // Комплектующие
  { id: 10, slug: 'smoant-coils', name: 'Испарители Smoant', category_slug: 'accessories', sort_order: 1, is_active: true },
  { id: 11, slug: 'geekvape-coils', name: 'Испарители Geekvape B-series', category_slug: 'accessories', sort_order: 2, is_active: true },
  { id: 12, slug: 'vaporesso-cartridges', name: 'Картриджи Vaporesso XROS', category_slug: 'accessories', sort_order: 3, is_active: true },
  { id: 13, slug: 'voopoo-coils', name: 'Испарители Voopoo PnP', category_slug: 'accessories', sort_order: 4, is_active: true },
  { id: 14, slug: 'nevoks-cartridges', name: 'Картриджи Nevoks Pagee/Feelin', category_slug: 'accessories', sort_order: 5, is_active: true },

  // POD-системы
  { id: 20, slug: 'geekvape-aegis', name: 'Geekvape (Aegis)', category_slug: 'pod', sort_order: 1, is_active: true },
  { id: 21, slug: 'vaporesso', name: 'Vaporesso (Xros/Luxe)', category_slug: 'pod', sort_order: 2, is_active: true },
  { id: 22, slug: 'smoant-devices', name: 'Smoant (Charon/Knight/Santi)', category_slug: 'pod', sort_order: 3, is_active: true },
  { id: 23, slug: 'voopoo', name: 'Voopoo (Drag/Vmate)', category_slug: 'pod', sort_order: 4, is_active: true },
  { id: 24, slug: 'ursa-lost-vape', name: 'Lost Vape Ursa Baby / Nano', category_slug: 'pod', sort_order: 5, is_active: true },

  // Одноразки
  { id: 30, slug: 'chillax', name: 'Chillax Plus / Neo', category_slug: 'disposable', sort_order: 1, is_active: true },
  { id: 31, slug: 'elfbar', name: 'Elf Bar 5000/10000', category_slug: 'disposable', sort_order: 2, is_active: true },
  { id: 32, slug: 'lost-mary', name: 'Lost Mary OS5000', category_slug: 'disposable', sort_order: 3, is_active: true },
  { id: 33, slug: 'waka', name: 'Waka Smash / soPro', category_slug: 'disposable', sort_order: 4, is_active: true },
  { id: 34, slug: 'plonq', name: 'Plonq Max Pro', category_slug: 'disposable', sort_order: 5, is_active: true },

  // Снюс
  { id: 40, slug: 'drymost', name: 'Drymost', category_slug: 'snus', sort_order: 1, is_active: true },
  { id: 41, slug: 'glitch', name: 'Glitch', category_slug: 'snus', sort_order: 2, is_active: true },
  { id: 42, slug: 'corvus', name: 'Corvus Brutal', category_slug: 'snus', sort_order: 3, is_active: true },
  { id: 43, slug: 'odens', name: "Oden's Cold Dry", category_slug: 'snus', sort_order: 4, is_active: true },
];

export const INITIAL_MODELS: ProductModel[] = [
  { id: 1, slug: 'aegis-boost-3', name: 'Aegis Boost 3', category_slug: 'pod', brand_slug: 'geekvape-aegis', sort_order: 1, is_active: true },
  { id: 2, slug: 'aegis-hero-2', name: 'Aegis Hero 2 (H45)', category_slug: 'pod', brand_slug: 'geekvape-aegis', sort_order: 2, is_active: true },
  { id: 3, slug: 'xros-4-pro', name: 'Vaporesso XROS 4 Pro', category_slug: 'pod', brand_slug: 'vaporesso', sort_order: 3, is_active: true },
  { id: 4, slug: 'xros-mini-3', name: 'Vaporesso XROS 3 Mini', category_slug: 'pod', brand_slug: 'vaporesso', sort_order: 4, is_active: true },
  { id: 5, slug: 'charon-baby-plus', name: 'Smoant Charon Baby Plus', category_slug: 'pod', brand_slug: 'smoant-devices', sort_order: 5, is_active: true },
  { id: 6, slug: 'knight-80', name: 'Smoant Knight 80', category_slug: 'pod', brand_slug: 'smoant-devices', sort_order: 6, is_active: true },
  { id: 7, slug: 'drag-s2', name: 'Voopoo Drag S2', category_slug: 'pod', brand_slug: 'voopoo', sort_order: 7, is_active: true },
];

export const INITIAL_ATTRIBUTE_GROUPS: AttributeGroup[] = [
  { id: 1, slug: 'liquid_strength', name: 'Крепость жидкости', category_slug: 'liquid', sort_order: 1, is_active: true },
  { id: 2, slug: 'liquid_brand_line', name: 'Линейка жидкости', category_slug: 'liquid', sort_order: 2, is_active: true },
  { id: 3, slug: 'snus_strength', name: 'Крепость снюса', category_slug: 'snus', sort_order: 3, is_active: true },
  { id: 4, slug: 'snus_line', name: 'Линейка снюса', category_slug: 'snus', sort_order: 4, is_active: true },
];

export const INITIAL_ATTRIBUTE_VALUES: AttributeValue[] = [
  { id: 1, attribute_group_slug: 'liquid_strength', value: '0 мг', sort_order: 1, is_active: true },
  { id: 2, attribute_group_slug: 'liquid_strength', value: '20-50 мг', sort_order: 2, is_active: true },
  { id: 3, attribute_group_slug: 'liquid_strength', value: '60-70 мг', sort_order: 3, is_active: true },
  { id: 4, attribute_group_slug: 'liquid_strength', value: '80+ мг', sort_order: 4, is_active: true },

  { id: 10, attribute_group_slug: 'liquid_brand_line', value: 'Husky White (Холодок)', sort_order: 1, is_active: true },
  { id: 11, attribute_group_slug: 'liquid_brand_line', value: 'Husky Mint Series', sort_order: 2, is_active: true },
  { id: 12, attribute_group_slug: 'liquid_brand_line', value: 'Подонки Анархия V2', sort_order: 3, is_active: true },
  { id: 13, attribute_group_slug: 'liquid_brand_line', value: 'Maxwells Shoria Original', sort_order: 4, is_active: true },
  { id: 14, attribute_group_slug: 'liquid_brand_line', value: 'Бошки Хвойный Микс', sort_order: 5, is_active: true },
  { id: 15, attribute_group_slug: 'liquid_brand_line', value: 'Glitch Sauce Iced Out', sort_order: 6, is_active: true },

  { id: 20, attribute_group_slug: 'snus_strength', value: '75 мг', sort_order: 1, is_active: true },
  { id: 21, attribute_group_slug: 'snus_strength', value: '150 мг', sort_order: 2, is_active: true },
  { id: 22, attribute_group_slug: 'snus_strength', value: '200 мг', sort_order: 3, is_active: true },

  { id: 30, attribute_group_slug: 'snus_line', value: 'Drymost Original', sort_order: 1, is_active: true },
  { id: 31, attribute_group_slug: 'snus_line', value: 'Glitch Strong', sort_order: 2, is_active: true },
  { id: 32, attribute_group_slug: 'snus_line', value: 'Corvus Brutal Extra', sort_order: 3, is_active: true },
];

export const INITIAL_PRODUCTS: Product[] = [
  // СКИДОЧНЫЕ ТОВАРЫ (Сейл)
  {
    id: 1,
    name: 'Husky White Salt (Сладкая мята & Арбуз)',
    price: 24.0,
    discount_price: 18.0,
    emoji: '🍉',
    category_slug: 'liquid',
    brand_slug: 'husky',
    stock_quantity: 18,
    in_stock: true,
    sold_count: 85,
    is_hit: true,
    is_new: false,
    description: 'Освежающий вкус арбузного фреша с морозной мятой. Объем: 30мл. Солевой никотин 20-50мг.',
  },
  {
    id: 2,
    name: 'Geekvape Aegis Hero 2 (H45) Pod Kit',
    price: 125.0,
    discount_price: 99.0,
    emoji: '💨',
    category_slug: 'pod',
    brand_slug: 'geekvape-aegis',
    model_slug: 'aegis-hero-2',
    stock_quantity: 7,
    in_stock: true,
    sold_count: 42,
    is_hit: true,
    is_new: false,
    description: 'Ударопрочный девайс IP67, емкий аккумулятор 1400 мАч, регулировка обдува верхнего забора воздуха (без протечек).',
  },
  {
    id: 3,
    name: 'DRYMOST 150мг (Ананасовый джем)',
    price: 22.0,
    discount_price: 16.0,
    emoji: '🍍',
    category_slug: 'snus',
    brand_slug: 'drymost',
    stock_quantity: 25,
    in_stock: true,
    sold_count: 94,
    is_hit: true,
    is_new: false,
    description: 'Яркий сладкий ананасовый джем с мощным эффектом. 20 порций в шайбе.',
  },
  {
    id: 4,
    name: 'Chillax Plus 6000 (Черника Лед)',
    price: 32.0,
    discount_price: 24.0,
    emoji: '🫐',
    category_slug: 'disposable',
    brand_slug: 'chillax',
    stock_quantity: 14,
    in_stock: true,
    sold_count: 67,
    is_hit: false,
    is_new: true,
    description: '6000 затяжек, порт зарядки Type-C, плотный и насыщенный вкус черничного льда.',
  },

  // ЖИДКОСТИ
  {
    id: 5,
    name: 'Подонки v2 (Малина-Клубника Экстра Лед)',
    price: 21.0,
    discount_price: null,
    emoji: '🍓',
    category_slug: 'liquid',
    brand_slug: 'podonki',
    stock_quantity: 30,
    in_stock: true,
    sold_count: 110,
    is_hit: true,
    is_new: true,
    description: 'Двойная малина с садовой клубникой и мощным ледяным кулером.',
  },
  {
    id: 6,
    name: 'Maxwells Shoria (Хвоя, мята, лесные ягоды)',
    price: 26.0,
    discount_price: null,
    emoji: '🌲',
    category_slug: 'liquid',
    brand_slug: 'maxwells',
    stock_quantity: 12,
    in_stock: true,
    sold_count: 78,
    is_hit: true,
    is_new: false,
    description: 'Культовый сибирский микс лесных ягод, свежей хвои и прохладной мяты.',
  },
  {
    id: 7,
    name: 'Бошки Садовые (Земляника с хвоей)',
    price: 19.5,
    discount_price: null,
    emoji: '🍃',
    category_slug: 'liquid',
    brand_slug: 'boshki',
    stock_quantity: 16,
    in_stock: true,
    sold_count: 53,
    is_hit: false,
    is_new: false,
    description: 'Спелая сладкая земляника в сочетании с терпкими еловыми нотками.',
  },
  {
    id: 8,
    name: 'Glitch Sauce Amber (Персик Манго)',
    price: 23.0,
    discount_price: null,
    emoji: '🍑',
    category_slug: 'liquid',
    brand_slug: 'glitch-sauce',
    stock_quantity: 20,
    in_stock: true,
    sold_count: 61,
    is_hit: false,
    is_new: false,
    description: 'Сочный сладкий персик и спелый тропический манго.',
  },
  {
    id: 9,
    name: 'Hotspot Fuel Extra (Ананас Кокос)',
    price: 22.5,
    discount_price: null,
    emoji: '🥥',
    category_slug: 'liquid',
    brand_slug: 'hotspot',
    stock_quantity: 15,
    in_stock: true,
    sold_count: 48,
    is_hit: false,
    is_new: true,
    description: 'Крепкий тропический коктейль пина колада со сверхнасыщенным ароматом.',
  },

  // POD-СИСТЕМЫ
  {
    id: 10,
    name: 'Vaporesso XROS 4 Pro Kit',
    price: 110.0,
    discount_price: 95.0,
    emoji: '⚡',
    category_slug: 'pod',
    brand_slug: 'vaporesso',
    model_slug: 'xros-4-pro',
    stock_quantity: 9,
    in_stock: true,
    sold_count: 55,
    is_hit: true,
    is_new: true,
    description: 'Топовая новинка от Vaporesso с экраном, аккумулятором 1200 мАч и регулировкой мощности до 30W.',
  },
  {
    id: 11,
    name: 'Smoant Charon Baby Plus',
    price: 79.0,
    discount_price: null,
    emoji: '✨',
    category_slug: 'pod',
    brand_slug: 'smoant-devices',
    model_slug: 'charon-baby-plus',
    stock_quantity: 11,
    in_stock: true,
    sold_count: 90,
    is_hit: true,
    is_new: false,
    description: 'Сменные 3D-панели, совместимость с испарителями Santi S-series, быстрая зарядка.',
  },
  {
    id: 12,
    name: 'Lost Vape Ursa Nano 2 Pod',
    price: 68.0,
    discount_price: null,
    emoji: '🔋',
    category_slug: 'pod',
    brand_slug: 'ursa-lost-vape',
    stock_quantity: 14,
    in_stock: true,
    sold_count: 38,
    is_hit: false,
    is_new: true,
    description: 'Стильный лазерный гравированный корпус, динамическая подсветка, бак на 2.5 мл.',
  },

  // КОМПЛЕКТУЮЩИЕ
  {
    id: 13,
    name: 'Испаритель Smoant Santi / Charon Plus S-3 (0.6 Ом)',
    price: 8.5,
    discount_price: null,
    emoji: '🔧',
    category_slug: 'accessories',
    brand_slug: 'smoant-coils',
    stock_quantity: 45,
    in_stock: true,
    sold_count: 140,
    is_hit: true,
    is_new: false,
    description: 'Сетчатый испаритель для плотного пара и отличной вкусопередачи (18-25 Вт).',
  },
  {
    id: 14,
    name: 'Испаритель Geekvape B-series (0.4 Ом)',
    price: 9.5,
    discount_price: null,
    emoji: '⚙️',
    category_slug: 'accessories',
    brand_slug: 'geekvape-coils',
    stock_quantity: 35,
    in_stock: true,
    sold_count: 98,
    is_hit: true,
    is_new: false,
    description: 'Подходит для Aegis Boost, Hero 1/2, M100. Мощная тяга и густой пар.',
  },
  {
    id: 15,
    name: 'Картридж Vaporesso XROS Corex 2.0 (0.6 Ом)',
    price: 9.0,
    discount_price: null,
    emoji: '🧪',
    category_slug: 'accessories',
    brand_slug: 'vaporesso-cartridges',
    stock_quantity: 60,
    in_stock: true,
    sold_count: 210,
    is_hit: true,
    is_new: true,
    description: 'Улучшенная версия картриджа Corex 2.0: дольше служит и ярче передает вкус.',
  },

  // ОДНОРАЗКИ
  {
    id: 16,
    name: 'Elf Bar BC10000 (Черника Малина Виноград)',
    price: 36.0,
    discount_price: 30.0,
    emoji: '🍇',
    category_slug: 'disposable',
    brand_slug: 'elfbar',
    stock_quantity: 12,
    in_stock: true,
    sold_count: 75,
    is_hit: true,
    is_new: true,
    description: '10000 затяжек, индикатор заряда и остатка жидкости, сетчатый испаритель QUAQ.',
  },
  {
    id: 17,
    name: 'Lost Mary OS5000 (Красное Яблоко)',
    price: 29.0,
    discount_price: null,
    emoji: '🍎',
    category_slug: 'disposable',
    brand_slug: 'lost-mary',
    stock_quantity: 18,
    in_stock: true,
    sold_count: 45,
    is_hit: false,
    is_new: false,
    description: 'Хрустящее сочное яблоко со сладким послевкусием.',
  },
  {
    id: 18,
    name: 'Waka soPro 10000 (Двойное Яблоко & Лед)',
    price: 38.0,
    discount_price: 32.0,
    emoji: '🍏',
    category_slug: 'disposable',
    brand_slug: 'waka',
    stock_quantity: 16,
    in_stock: true,
    sold_count: 82,
    is_hit: true,
    is_new: true,
    description: 'Двойная сетка Boost Mode для экстра-пара и вкуса.',
  },

  // СНЮС
  {
    id: 19,
    name: 'Glitch 200мг (Арктическая Мята)',
    price: 24.0,
    discount_price: null,
    emoji: '🧊',
    category_slug: 'snus',
    brand_slug: 'glitch',
    stock_quantity: 22,
    in_stock: true,
    sold_count: 88,
    is_hit: true,
    is_new: false,
    description: 'Ультра-крепкий бестабачный снюс с мощным ледяным мятным жжением.',
  },
  {
    id: 20,
    name: 'Corvus Brutal Extra 150мг (Ледяная Мята)',
    price: 23.0,
    discount_price: null,
    emoji: '💨',
    category_slug: 'snus',
    brand_slug: 'corvus',
    stock_quantity: 17,
    in_stock: true,
    sold_count: 65,
    is_hit: false,
    is_new: false,
    description: 'Классический белый порционный снюс высокой крепости.',
  },
];

export const INITIAL_PRODUCT_COLORS: ProductColor[] = [
  { id: 1, product_id: 2, color_name: 'Черный карбон (Black)', color_hex: '#18181b', stock_quantity: 3, sort_order: 1 },
  { id: 2, product_id: 2, color_name: 'Фиолетовый градиент (Rainbow)', color_hex: '#a855f7', stock_quantity: 2, sort_order: 2 },
  { id: 3, product_id: 2, color_name: 'Красный металлик (Red)', color_hex: '#ef4444', stock_quantity: 2, sort_order: 3 },
  { id: 4, product_id: 10, color_name: 'Midnight Black', color_hex: '#09090b', stock_quantity: 4, sort_order: 1 },
  { id: 5, product_id: 10, color_name: 'Lilac Purple', color_hex: '#c084fc', stock_quantity: 3, sort_order: 2 },
  { id: 6, product_id: 10, color_name: 'Sunset Orange', color_hex: '#f97316', stock_quantity: 2, sort_order: 3 },
  { id: 7, product_id: 11, color_name: 'Space Grey', color_hex: '#4b5563', stock_quantity: 6, sort_order: 1 },
  { id: 8, product_id: 11, color_name: 'Neon Cyberpunk', color_hex: '#8b5cf6', stock_quantity: 5, sort_order: 2 },
];

export const INITIAL_PICKUP_POINTS: PickupPoint[] = [
  {
    id: 1,
    name: 'Минск: ст.м. Площадь Якуба Коласа',
    address: 'ул. Веры Хоружей, 1А (ТЦ Силуэт, 2 этаж)',
    working_hours: 'Ежедневно с 11:00 до 21:00',
    comment: 'Выдача у администратора после подтверждения',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 2,
    name: 'Минск: ст.м. Каменная Горка',
    address: 'ул. Притыцкого, 156 (ТЦ Green City)',
    working_hours: 'Ежедневно с 12:00 до 22:00',
    comment: 'У главного входа по согласованию с курьером',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 3,
    name: 'Минск: ст.м. Институт Культуры',
    address: 'ул. Могилевская, 5 (рядом с метро)',
    working_hours: 'Пн-Сб с 13:00 до 20:00',
    comment: 'Личная встреча в течение 30 минут',
    is_active: true,
    sort_order: 3,
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 1,
    title: '🎁 Каждый 5-й заказ — подарок от шопа!',
    short_description: 'Оформите 4 заказа и получите бесплатную фирменную жидкость или одноразку!',
    description:
      'Мы ценим постоянных клиентов Puff Paradise! За каждые 4 успешно выполненных заказа вы получаете гарантированный подарок к вашему 5-му заказу на выбор (премиальная жидкость 30мл или скидка 50% на одноразку).',
    condition_text: 'Для постоянных покупателей',
    image_emoji: '🎁',
    button_text: 'Написать менеджеру',
    button_url: 'https://t.me/puff_mngr',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 2,
    title: '🎂 Скидка 10% именинникам в день рождения!',
    short_description: 'Покажите дату в Telegram или паспорт и получите приятный бонус на любой заказ!',
    description:
      'Празднуешь день рождения? Дарим скидку 10% на весь ассортимент (жидкости, одноразки, POD-системы) в день рождения и за 2 дня до/после него! Напиши нашему менеджеру перед оформлением.',
    condition_text: 'Скидка 10%',
    image_emoji: '🎉',
    button_text: 'Получить скидку @puff_mngr',
    button_url: 'https://t.me/puff_mngr',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 3,
    title: '🚚 Бесплатная доставка от 4 позиций!',
    short_description: 'Добавили в корзину от 4 любых товаров? Доставка по Минску за наш счет!',
    description:
      'Заказывай больше и экономь на доставке! При заказе от 4 любых позиций (например 2 жижи + 2 испарика или 4 одноразки) курьер доставит заказ бесплатно.',
    condition_text: 'Экономия 5 BYN',
    image_emoji: '🚚',
    button_text: 'Перейти в каталог',
    button_url: '',
    is_active: true,
    sort_order: 3,
  },
];

export const INITIAL_PROMOCODES: Promocode[] = [
  {
    id: 1,
    code: 'PUFF2026',
    discount_type: 'percent',
    discount_value: 10,
    min_order_amount: 20,
    max_uses: 500,
    used_count: 34,
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 2,
    code: 'PARADISE5',
    discount_type: 'fixed',
    discount_value: 5,
    min_order_amount: 30,
    max_uses: 200,
    used_count: 18,
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 3,
    code: 'NEW15',
    discount_type: 'percent',
    discount_value: 15,
    min_order_amount: 40,
    max_uses: 100,
    used_count: 12,
    valid_until: '2026-12-31',
    is_active: true,
  },
];

export const INITIAL_ADMINS: AdminUser[] = [
  { id: 1, user_id: 5659638424, username: 'puff_owner', role: 'admin', is_active: true },
  { id: 2, user_id: 8161417737, username: 'puff_admin', role: 'admin', is_active: true },
  { id: 3, user_id: 999999999, username: 'puff_moderator', role: 'moderator', is_active: true },
];
