import {
  Category,
  Brand,
  ProductModel,
  AttributeGroup,
  AttributeValue,
  Product,
  ProductColor,
  PickupPoint,
  Promotion,
  Promocode,
  ShopSettings,
  AdminUser,
} from '../types';

export const INITIAL_SETTINGS: ShopSettings = {
  welcome_title: 'Добро пожаловать в Puff Paradise Shop',
  welcome_description:
    'Официальный каталог Puff Paradise в Могилеве: оригинальные жидкости, POD-системы Vaporesso, испарители, картриджи, одноразки и снюс. Быстрая доставка по Могилеву и Беларуси, самовывоз из удобных точек!',
  logo_url: '',
  delivery_price: 5.0,
  free_delivery_min_items: 4,
  manager_username: 'puff_mngr',
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 1, slug: 'liquid', name: 'Жидкости', icon: '🧪', sort_order: 1, is_active: true },
  { id: 2, slug: 'pods', name: 'POD-системы', icon: '🔋', sort_order: 2, is_active: true },
  { id: 3, slug: 'consumables', name: 'Расходники', icon: '⚡', sort_order: 3, is_active: true },
  { id: 4, slug: 'disposable', name: 'Одноразки', icon: '💨', sort_order: 4, is_active: true },
  { id: 5, slug: 'snus', name: 'Снюс и паучи', icon: '❄️', sort_order: 5, is_active: true },
];

export const INITIAL_BRANDS: Brand[] = [
  // Жидкости
  { id: 1, slug: 'bjorn', name: 'BJORN ZLOY V1 (60mg)', category_slug: 'liquid', sort_order: 1, is_active: true },
  { id: 2, slug: 'catswill', name: 'CATSWILL Classic (20mg)', category_slug: 'liquid', sort_order: 2, is_active: true },
  { id: 3, slug: 'podonki', name: 'PODONKI Podgon (50mg)', category_slug: 'liquid', sort_order: 3, is_active: true },
  { id: 4, slug: 'anarchia', name: 'Анархия V2 (70mg)', category_slug: 'liquid', sort_order: 4, is_active: true },
  { id: 5, slug: 'ubivashka', name: 'УБИВАШКА (80mg)', category_slug: 'liquid', sort_order: 5, is_active: true },

  // POD-системы
  { id: 10, slug: 'vaporesso', name: 'Vaporesso (Xros Series)', category_slug: 'pods', sort_order: 1, is_active: true },

  // Расходники (Испарители & Картриджи)
  { id: 20, slug: 'vaporesso-cartridges', name: 'Картриджи Vaporesso XROS', category_slug: 'consumables', sort_order: 1, is_active: true },
  { id: 21, slug: 'voopoo', name: 'Картриджи VOOPOO VMATE', category_slug: 'consumables', sort_order: 2, is_active: true },
  { id: 22, slug: 'geekvape', name: 'Испарители Geekvape Aegis', category_slug: 'consumables', sort_order: 3, is_active: true },

  // Одноразки
  { id: 30, slug: 'puffup', name: 'PUFFUP 5000', category_slug: 'disposable', sort_order: 1, is_active: true },

  // Снюс
  { id: 40, slug: 'drymost', name: 'DRYMOST Armageddon (200mg)', category_slug: 'snus', sort_order: 1, is_active: true },
  { id: 41, slug: 'glitch', name: 'GLITCH Pouches (150mg)', category_slug: 'snus', sort_order: 2, is_active: true },
];

export const INITIAL_MODELS: ProductModel[] = [
  { id: 1, slug: 'xros-5-mini', name: 'Vaporesso Xros 5 Mini', category_slug: 'pods', brand_slug: 'vaporesso', sort_order: 1, is_active: true },
  { id: 2, slug: 'xros-6-mini', name: 'Vaporesso Xros 6 Mini', category_slug: 'pods', brand_slug: 'vaporesso', sort_order: 2, is_active: true },
];

export const INITIAL_ATTRIBUTE_GROUPS: AttributeGroup[] = [
  { id: 1, slug: 'liquid_strength', name: 'Крепость жидкости', category_slug: 'liquid', sort_order: 1, is_active: true },
  { id: 2, slug: 'liquid_brand_line', name: 'Линейка жидкости', category_slug: 'liquid', sort_order: 2, is_active: true },
  { id: 3, slug: 'snus_strength', name: 'Крепость снюса', category_slug: 'snus', sort_order: 3, is_active: true },
];

export const INITIAL_ATTRIBUTE_VALUES: AttributeValue[] = [
  { id: 1, attribute_group_slug: 'liquid_strength', value: '20 мг', sort_order: 1, is_active: true },
  { id: 2, attribute_group_slug: 'liquid_strength', value: '50 мг', sort_order: 2, is_active: true },
  { id: 3, attribute_group_slug: 'liquid_strength', value: '60 мг', sort_order: 3, is_active: true },
  { id: 4, attribute_group_slug: 'liquid_strength', value: '70 мг', sort_order: 4, is_active: true },
  { id: 5, attribute_group_slug: 'liquid_strength', value: '80 мг', sort_order: 5, is_active: true },

  { id: 10, attribute_group_slug: 'liquid_brand_line', value: 'BJORN ZLOY V1', sort_order: 1, is_active: true },
  { id: 11, attribute_group_slug: 'liquid_brand_line', value: 'CATSWILL Classic', sort_order: 2, is_active: true },
  { id: 12, attribute_group_slug: 'liquid_brand_line', value: 'PODONKI Podgon', sort_order: 3, is_active: true },
  { id: 13, attribute_group_slug: 'liquid_brand_line', value: 'Анархия V2', sort_order: 4, is_active: true },
  { id: 14, attribute_group_slug: 'liquid_brand_line', value: 'УБИВАШКА 80mg', sort_order: 5, is_active: true },

  { id: 20, attribute_group_slug: 'snus_strength', value: '150 мг', sort_order: 1, is_active: true },
  { id: 21, attribute_group_slug: 'snus_strength', value: '200 мг', sort_order: 2, is_active: true },
];

export const INITIAL_PRODUCTS: Product[] = [
  // ================= 1. BJORN ZLOY V1 60mg (8.50 BYN) =================
  {
    id: 1,
    name: 'Жидкость BJORN ZLOY V1 60mg - 2 Арбузная жвачка',
    price: 8.5,
    emoji: '🍉',
    category_slug: 'liquid',
    brand_slug: 'bjorn',
    description: 'Крепость: 60 мг · Вкус: Насыщенная арбузная жвачка с холодком',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 2,
    name: 'Жидкость BJORN ZLOY V1 60mg - 8 Дыня ананас',
    price: 8.5,
    emoji: '🍍',
    category_slug: 'liquid',
    brand_slug: 'bjorn',
    description: 'Крепость: 60 мг · Вкус: Сладкая медовая дыня и спелый тропический ананас',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 3,
    name: 'Жидкость BJORN ZLOY V1 60mg - 9 Киви клубника',
    price: 8.5,
    emoji: '🥝',
    category_slug: 'liquid',
    brand_slug: 'bjorn',
    description: 'Крепость: 60 мг · Вкус: Сочный киви и спелая садовая клубника',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 4,
    name: 'Жидкость BJORN ZLOY V1 60mg - B21 Скитлс',
    price: 8.5,
    emoji: '🍬',
    category_slug: 'liquid',
    brand_slug: 'bjorn',
    description: 'Крепость: 60 мг · Вкус: Разноцветные фруктовые драже Скитлс',
    stock_quantity: 10,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 5,
    name: 'Жидкость BJORN ZLOY V1 60mg - B22 Смородина черника лимон',
    price: 8.5,
    emoji: '🫐',
    category_slug: 'liquid',
    brand_slug: 'bjorn',
    description: 'Крепость: 60 мг · Вкус: Черная смородина, лесная черника и кислый лимон',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 6,
    name: 'Жидкость BJORN ZLOY V1 60mg - B24 Энергетик виноград',
    price: 8.5,
    emoji: '⚡',
    category_slug: 'liquid',
    brand_slug: 'bjorn',
    description: 'Крепость: 60 мг · Вкус: Бодрящий энергетический напиток с темным виноградом',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 2. CATSWILL CLASSIC 20mg (8.65 BYN) =================
  {
    id: 7,
    name: 'Жидкость CATSWILL 20mg - Кислый виноградный чупа чупс',
    price: 8.65,
    emoji: '🍭',
    category_slug: 'liquid',
    brand_slug: 'catswill',
    description: 'Крепость: 20 мг · Вкус: Кислый виноградный леденец чупа-чупс',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 8,
    name: 'Жидкость CATSWILL 20mg - Кислый малиновый скитлс',
    price: 8.65,
    emoji: '🍬',
    category_slug: 'liquid',
    brand_slug: 'catswill',
    description: 'Крепость: 20 мг · Вкус: Кислая малина и конфеты скитлс',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 9,
    name: 'Жидкость CATSWILL 20mg - Мамба кислое яблоко киви (без коробочки)',
    price: 8.65,
    emoji: '🍏',
    category_slug: 'liquid',
    brand_slug: 'catswill',
    description: 'Крепость: 20 мг · Вкус: Жевательная конфета Мамба с кислым яблоком и киви',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 3. PODONKI PODGON 50mg (5.75 BYN) =================
  {
    id: 10,
    name: 'Жидкость PODONKI Podgon 50mg - 2 Ананасовая газировка',
    price: 5.75,
    emoji: '🍍',
    category_slug: 'liquid',
    brand_slug: 'podonki',
    description: 'Крепость: 50 мг · Вкус: Освежающая шипучая ананасовая газировка со льдом',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 11,
    name: 'Жидкость PODONKI Podgon 50mg - 8 Ежевика черника',
    price: 5.75,
    emoji: '🫐',
    category_slug: 'liquid',
    brand_slug: 'podonki',
    description: 'Крепость: 50 мг · Вкус: Спелая лесная ежевика и сладкая черника',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 12,
    name: 'Жидкость PODONKI Podgon 50mg - A14 Классический бабл гам',
    price: 5.75,
    emoji: '🫧',
    category_slug: 'liquid',
    brand_slug: 'podonki',
    description: 'Крепость: 50 мг · Вкус: Розовая жевательная резинка бабл гам',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 13,
    name: 'Жидкость PODONKI Podgon 50mg - B28 Скитлз',
    price: 5.75,
    emoji: '🌈',
    category_slug: 'liquid',
    brand_slug: 'podonki',
    description: 'Крепость: 50 мг · Вкус: Радужные фруктовые драже Skittles',
    stock_quantity: 10,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 4. Анархия V2 70mg (7.90 BYN) =================
  {
    id: 14,
    name: 'Жидкость Анархия V2 70mg - Арбузно-клубничный коктейль (3)',
    price: 7.9,
    emoji: '🍓',
    category_slug: 'liquid',
    brand_slug: 'anarchia',
    description: 'Крепость: 70 мг · Вкус: Освежающий арбузно-клубничный коктейль',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 15,
    name: 'Жидкость Анархия V2 70mg - Вишня лайм (6)',
    price: 7.9,
    emoji: '🍒',
    category_slug: 'liquid',
    brand_slug: 'anarchia',
    description: 'Крепость: 70 мг · Вкус: Спелая садовая вишня с кислинкой лайма',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 16,
    name: 'Жидкость Анархия V2 70mg - Голубая малина розовая малина арбуз (7)',
    price: 7.9,
    emoji: '🫐',
    category_slug: 'liquid',
    brand_slug: 'anarchia',
    description: 'Крепость: 70 мг · Вкус: Тройной взрывной микс Blue Razz, малина и сочный арбуз',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 17,
    name: 'Жидкость Анархия V2 70mg - Жвачка арбуз дыня (8)',
    price: 7.9,
    emoji: '🍉',
    category_slug: 'liquid',
    brand_slug: 'anarchia',
    description: 'Крепость: 70 мг · Вкус: Жвачка со сладким арбузом и медовой дыней',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 18,
    name: 'Жидкость Анархия V2 70mg - Лесные ягоды (17)',
    price: 7.9,
    emoji: '🫐',
    category_slug: 'liquid',
    brand_slug: 'anarchia',
    description: 'Крепость: 70 мг · Вкус: Ароматный сбор спелых диких лесных ягод',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 19,
    name: 'Жидкость Анархия V2 70mg - Манго малина (20)',
    price: 7.9,
    emoji: '🥭',
    category_slug: 'liquid',
    brand_slug: 'anarchia',
    description: 'Крепость: 70 мг · Вкус: Тропическое спелое манго и садовая малина',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 5. УБИВАШКА 80mg (9.00 BYN) =================
  {
    id: 20,
    name: 'Жидкость УБИВАШКА 80mg - Виноградная фанта (2)',
    price: 9.0,
    emoji: '🍇',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Газировка Виноградная Фанта',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 21,
    name: 'Жидкость УБИВАШКА 80mg - Арбузный адреналин (1)',
    price: 9.0,
    emoji: '🍉',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Энергетический напиток с ледяным арбузом',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 22,
    name: 'Жидкость УБИВАШКА 80mg - Вишня лайм (5)',
    price: 9.0,
    emoji: '🍒',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Пряная вишня с терпким лаймом',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 23,
    name: 'Жидкость УБИВАШКА 80mg - Вишня яблоко (6)',
    price: 9.0,
    emoji: '🍎',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Кисло-сладкий коктейль из яблока и вишни',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 24,
    name: 'Жидкость УБИВАШКА 80mg - Кислая вишня ред булл смородина (9)',
    price: 9.0,
    emoji: '🥫',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Энергетик Ред Булл, кислая вишня и смородина',
    stock_quantity: 10,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 25,
    name: 'Жидкость УБИВАШКА 80mg - Клубнично арбузный скитлс (12)',
    price: 9.0,
    emoji: '🍬',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Скитлс со вкусом клубники и арбуза',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 26,
    name: 'Жидкость УБИВАШКА 80mg - Фруктовые леденцы (23)',
    price: 9.0,
    emoji: '🍭',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Насыщенные фруктовые леденцы монпансье',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 27,
    name: 'Жидкость УБИВАШКА 80mg - Энергетик классический (26)',
    price: 9.0,
    emoji: '⚡',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Оригинальный классический энергетик',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 28,
    name: 'Жидкость УБИВАШКА 80mg - Ягодный взрыв (29)',
    price: 9.0,
    emoji: '💥',
    category_slug: 'liquid',
    brand_slug: 'ubivashka',
    description: 'Экстра-крепость: 80 мг · Вкус: Взрывной коктейль из спелых лесных и садовых ягод',
    stock_quantity: 10,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 6. GEEK VAPE Испарители (6.00 BYN) =================
  {
    id: 29,
    name: 'Испаритель Aegis Hero/Boost 0.15 Ω (60 - 75 Ватт)',
    price: 6.0,
    emoji: '⚡',
    category_slug: 'consumables',
    brand_slug: 'geekvape',
    description: 'Оригинальный испаритель Geekvape B-Series Coil для Aegis Hero / Boost (0.15 Ом, 60-75W)',
    stock_quantity: 15,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 30,
    name: 'Испаритель Aegis Hero/Boost 0.3 Ω (30 - 38 Ватт)',
    price: 6.0,
    emoji: '⚡',
    category_slug: 'consumables',
    brand_slug: 'geekvape',
    description: 'Оригинальный испаритель Geekvape B-Series Coil для Aegis Hero / Boost (0.3 Ом, 30-38W)',
    stock_quantity: 15,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 7. VOOPOO Картриджи (6.00 BYN) =================
  {
    id: 31,
    name: 'Картридж VMATE V2 TOP FILL - 0.7 ohm',
    price: 6.0,
    emoji: '🔋',
    category_slug: 'consumables',
    brand_slug: 'voopoo',
    description: 'Картридж VOOPOO VMATE V2 с удобной верхней заправкой (Top Fill, 0.7 Ом)',
    stock_quantity: 20,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 8. VAPORESSO Картриджи (6.00 BYN) =================
  {
    id: 32,
    name: 'Картридж XROS 0.4 ohm COREX 3.0 (3 мл)',
    price: 6.0,
    emoji: '💨',
    category_slug: 'consumables',
    brand_slug: 'vaporesso-cartridges',
    description: 'Оригинальный картридж Vaporesso XROS с технологией COREX 3.0 и увеличенным объемом 3 мл (0.4 Ом)',
    stock_quantity: 25,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 33,
    name: 'Картридж XROS 0.6 ohm COREX 3.0 (3 мл)',
    price: 6.0,
    emoji: '💨',
    category_slug: 'consumables',
    brand_slug: 'vaporesso-cartridges',
    description: 'Оригинальный картридж Vaporesso XROS с технологией COREX 3.0 и объемом 3 мл (0.6 Ом)',
    stock_quantity: 25,
    in_stock: true,
    is_hit: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 9. PUFFUP 5000 Одноразки (5.00 BYN) =================
  {
    id: 34,
    name: 'Одноразовое устройство PUFFUP 5000 - Зеленое яблоко со льдом',
    price: 5.0,
    emoji: '🍏',
    category_slug: 'disposable',
    brand_slug: 'puffup',
    description: 'Одноразка на 5000 затяжек с подзарядкой Type-C. Вкус: Хрустящее зеленое яблоко со льдом',
    stock_quantity: 10,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 35,
    name: 'Одноразовое устройство PUFFUP 5000 - Клюквенно-лимонный сок',
    price: 5.0,
    emoji: '🍋',
    category_slug: 'disposable',
    brand_slug: 'puffup',
    description: 'Одноразка на 5000 затяжек с подзарядкой Type-C. Вкус: Освежающий клюквенно-лимонный морс',
    stock_quantity: 10,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 36,
    name: 'Одноразовое устройство PUFFUP 5000 - Ледяной ананас',
    price: 5.0,
    emoji: '🍍',
    category_slug: 'disposable',
    brand_slug: 'puffup',
    description: 'Одноразка на 5000 затяжек с подзарядкой Type-C. Вкус: Спелый тропический ананас с холодком',
    stock_quantity: 10,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 10. DRYMOST ARMAGEDDON 200MG (8.25 BYN) =================
  {
    id: 37,
    name: 'Снюс DRYMOST ARMAGEDDON 200mg - Газировка Доктор Пеппер',
    price: 8.25,
    emoji: '🥤',
    category_slug: 'snus',
    brand_slug: 'drymost',
    description: 'Бестабачные жевательные паучи. Крепость: 200 мг · Вкус: Газировка Dr. Pepper',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 38,
    name: 'Снюс DRYMOST ARMAGEDDON 200mg - Грейпфрутовый апельсин',
    price: 8.25,
    emoji: '🍊',
    category_slug: 'snus',
    brand_slug: 'drymost',
    description: 'Бестабачные жевательные паучи. Крепость: 200 мг · Вкус: Сочный грейпфрут и апельсин',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 39,
    name: 'Снюс DRYMOST ARMAGEDDON 200mg - Малина лимон',
    price: 8.25,
    emoji: '🍋',
    category_slug: 'snus',
    brand_slug: 'drymost',
    description: 'Бестабачные жевательные паучи. Крепость: 200 мг · Вкус: Садовая малина с лимоном',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 40,
    name: 'Снюс DRYMOST ARMAGEDDON 200mg - Маракуйя клубника',
    price: 8.25,
    emoji: '🍓',
    category_slug: 'snus',
    brand_slug: 'drymost',
    description: 'Бестабачные жевательные паучи. Крепость: 200 мг · Вкус: Экзотическая маракуйя и клубника',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 41,
    name: 'Снюс DRYMOST ARMAGEDDON 200mg - Яблоко смородина',
    price: 8.25,
    emoji: '🍏',
    category_slug: 'snus',
    brand_slug: 'drymost',
    description: 'Бестабачные жевательные паучи. Крепость: 200 мг · Вкус: Зеленое яблоко и спелая черная смородина',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 11. GLITCH POUCHES 150MG (7.75 BYN) =================
  {
    id: 42,
    name: 'Снюс GLITCH POUCHES 150 mg - Апельсиновая газировка',
    price: 7.75,
    emoji: '🍊',
    category_slug: 'snus',
    brand_slug: 'glitch',
    description: 'Паучи высокой крепости. Крепость: 150 мг · Вкус: Освежающая апельсиновая газировка',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 43,
    name: 'Снюс GLITCH POUCHES 150 mg - Двойная мята с вишней',
    price: 7.75,
    emoji: '🍒',
    category_slug: 'snus',
    brand_slug: 'glitch',
    description: 'Паучи высокой крепости. Крепость: 150 мг · Вкус: Двойная перечная мята со сладкой вишней',
    stock_quantity: 10,
    in_stock: true,
    created_at: '2026-08-26T10:00:00Z',
  },

  // ================= 12. POD-СИСТЕМЫ VAPORESSO =================
  {
    id: 44,
    name: 'Устройство Vaporesso Xros 5 Mini - Mist White (кожаный)',
    price: 31.0,
    emoji: '🤍',
    category_slug: 'pods',
    brand_slug: 'vaporesso',
    model_slug: 'xros-5-mini',
    description: 'POD-система нового поколения Vaporesso Xros 5 Mini в отделке из белой эко-кожи (Mist White). Батарея 1000 мАч, плавная регулировка затяжки, поддержка картриджей COREX 3.0.',
    stock_quantity: 5,
    in_stock: true,
    is_hit: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 45,
    name: 'Устройство Vaporesso Xros 5 Mini - Mist Black (кожаный)',
    price: 31.0,
    emoji: '🖤',
    category_slug: 'pods',
    brand_slug: 'vaporesso',
    model_slug: 'xros-5-mini',
    description: 'POD-система нового поколения Vaporesso Xros 5 Mini в стильной черной коже (Mist Black). Автозатяжка, быстрая зарядка Type-C.',
    stock_quantity: 5,
    in_stock: true,
    is_hit: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 46,
    name: 'Устройство Vaporesso Xros 6 Mini - Jelly Green (Ярко-зеленый)',
    price: 41.0,
    emoji: '💚',
    category_slug: 'pods',
    brand_slug: 'vaporesso',
    model_slug: 'xros-6-mini',
    description: 'Флагманская POD-система Vaporesso Xros 6 Mini в ярком прозрачно-зеленом корпусе (Jelly Green). Улучшенная плата Axon, чистейшая вкусопередача COREX 3.0.',
    stock_quantity: 3,
    in_stock: true,
    is_new: true,
    created_at: '2026-08-26T10:00:00Z',
  },
];

export const INITIAL_PRODUCT_COLORS: ProductColor[] = [
  { id: 1, product_id: 44, color_name: 'Mist White (Белая кожа)', color_hex: '#f8fafc', stock_quantity: 5 },
  { id: 2, product_id: 45, color_name: 'Mist Black (Черная кожа)', color_hex: '#18181b', stock_quantity: 5 },
  { id: 3, product_id: 46, color_name: 'Jelly Green (Ярко-зеленый)', color_hex: '#22c55e', stock_quantity: 3 },
];

export const INITIAL_PICKUP_POINTS: PickupPoint[] = [
  {
    id: 1,
    name: 'ТЦ Днепр (Центр · ул. Первомайская)',
    address: 'г. Могилев, ул. Первомайская, 29',
    working_hours: 'Ежедневно с 10:00 до 21:00',
    comment: 'Встреча у главного входа в ТЦ или на парковке',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 2,
    name: 'Пешеходная (ул. Ленинская · Ратуша)',
    address: 'г. Могилев, ул. Ленинская, 41',
    working_hours: 'Ежедневно с 11:00 до 22:00',
    comment: 'Личная встреча в центре города по согласованию',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 3,
    name: 'ТЦ Парк Сити (ул. Мовчанского / Габровская)',
    address: 'г. Могилев, ул. Мовчанского, 6',
    working_hours: 'Пн-Вс с 10:00 до 21:30',
    comment: 'Встреча у центрального входа',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 4,
    name: 'Народного Ополчения (Европочта)',
    address: 'г. Могилев, ул. Народного Ополчения, 18',
    working_hours: 'Ежедневно с 10:00 до 20:00',
    comment: 'Точка самовывоза и отправки заказов',
    is_active: true,
    sort_order: 4,
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 1,
    title: '🎁 Каждый 5-й заказ — подарок от шопа!',
    short_description: 'Оформите 4 заказа в Могилеве и получите бесплатный подарок к 5-му!',
    description:
      'Мы ценим постоянных клиентов Puff Paradise! За каждые 4 успешно выполненных заказа вы получаете гарантированный подарок к вашему 5-му заказу на выбор (жидкость BJORN/PODONKI или скидка на картриджи/одноразки).',
    condition_text: 'Для постоянных покупателей',
    image_emoji: '🎁',
    button_text: 'Написать менеджеру',
    button_url: 'https://t.me/puff_mngr',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 2,
    title: '🎂 Скидка 10% именинникам в день рождения!',
    short_description: 'Покажите дату в Telegram и получите приятный бонус на любой заказ!',
    description:
      'Празднуешь день рождения? Дарим скидку 10% на весь ассортимент (жидкости, одноразки, POD-системы Vaporesso) в день рождения и за 2 дня до/после него! Напиши нашему менеджеру перед оформлением.',
    condition_text: 'Скидка 10%',
    image_emoji: '🎉',
    button_text: 'Получить скидку @puff_mngr',
    button_url: 'https://t.me/puff_mngr',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 3,
    title: '🚚 Бесплатная доставка по Могилеву от 4 позиций!',
    short_description: 'Добавили в корзину от 4 любых товаров? Доставка по Могилеву за наш счет!',
    description:
      'Заказывай больше и экономь на доставке! При заказе от 4 любых позиций (например 2 жижи + 2 картриджа или 4 одноразки) курьер доставит заказ по Могилеву абсолютно бесплатно.',
    condition_text: 'Экономия 5 BYN',
    image_emoji: '🚚',
    button_text: 'Перейти в каталог',
    button_url: '',
    is_active: true,
    sort_order: 3,
  },
];

export const INITIAL_PROMOCODES: Promocode[] = [
  {
    id: 1,
    code: 'PUFF2026',
    discount_type: 'percent',
    discount_value: 10,
    min_order_amount: 20,
    max_uses: 500,
    used_count: 0,
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 2,
    code: 'MOGILEV5',
    discount_type: 'fixed',
    discount_value: 5,
    min_order_amount: 25,
    max_uses: 300,
    used_count: 0,
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 3,
    code: 'NEW15',
    discount_type: 'percent',
    discount_value: 15,
    min_order_amount: 35,
    max_uses: 100,
    used_count: 0,
    valid_until: '2026-12-31',
    is_active: true,
  },
];

export const INITIAL_ADMINS: AdminUser[] = [
  { id: 1, user_id: 5659638424, username: 'puff_owner', role: 'admin', is_active: true },
  { id: 2, user_id: 8161417737, username: 'puff_admin', role: 'admin', is_active: true },
];
